#ifndef _EOKAS_UI_MAIN_H_
#define _EOKAS_UI_MAIN_H_

#include "UIKey.h"
#include "UIPrimitive.h"
#include "UIShape.h"
#include "UIWidget.h"
#include "UIFrame.h"
#include "widgets/UIImage.h"
#include "widgets/UIText.h"
#include "widgets/UIList.h"
#include "widgets/UIGrid.h"
#include "widgets/UITable.h"
#include "widgets/UIView.h"
#include "widgets/UICanvas.h"
#include "widgets/UIChart.h"
#include "charts/UIEllipse.h"
#include "charts/UIRectangle.h"
#include "charts/UIDiamond.h"
#include "charts/UILink.h"
#include "UIFont.h"
#include "widgets/UIMenu.h"
#include "widgets/UIButton.h"
#include "widgets/UISlider.h"
#include "widgets/UIToggle.h"
#include "widgets/UIInput.h"
#include "widgets/UIDropdown.h"
#include "widgets/UIRegion.h"
#include "widgets/UIDocking.h"
#include "UIApp.h"

#endif//_EOKAS_UI_MAIN_H_
