message("========================================================================")
message("== EOKAS UNIT TESTS")
message("========================================================================")

set(EOKAS_UNIT_ENGINE_DIR "${CMAKE_CURRENT_LIST_DIR}/engine")
set(EOKAS_UNIT_CASES_DIR "${CMAKE_CURRENT_LIST_DIR}/cases")

function(eokas_unit_walk TARGET_NAME)
    if(NOT TARGET "${TARGET_NAME}")
        return()
    endif()
    get_property(seen GLOBAL PROPERTY EOKAS_UNIT_SEEN)
    if("${TARGET_NAME}" IN_LIST seen)
        return()
    endif()
    set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_SEEN "${TARGET_NAME}")

    foreach(prop INCLUDE_DIRECTORIES LINK_DIRECTORIES COMPILE_DEFINITIONS)
        get_target_property(values "${TARGET_NAME}" "${prop}")
        if(values AND NOT "${values}" MATCHES "NOTFOUND")
            if(prop STREQUAL "INCLUDE_DIRECTORIES")
                set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_INCLUDES ${values})
            elseif(prop STREQUAL "LINK_DIRECTORIES")
                set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_LIBDIRS ${values})
            else()
                set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_DEFS ${values})
            endif()
        endif()
    endforeach()

    get_target_property(libs "${TARGET_NAME}" LINK_LIBRARIES)
    if(NOT libs OR "${libs}" MATCHES "NOTFOUND")
        return()
    endif()
    foreach(lib ${libs})
        if(lib STREQUAL "optimized" OR lib STREQUAL "debug" OR lib STREQUAL "general")
            continue()
        endif()
        if(lib STREQUAL "fbxsdk")
            set(lib "libfbxsdk")
        endif()
        if(TARGET "${lib}")
            set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_LIBS "${lib}")
            eokas_unit_walk("${lib}")
        else()
            set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_LIBS "${lib}")
        endif()
    endforeach()
endfunction()

function(eokas_add_unit_module MODULE_NAME)
    set(CASE_DIR "${EOKAS_UNIT_CASES_DIR}/${MODULE_NAME}")
    if(NOT IS_DIRECTORY "${CASE_DIR}")
        return()
    endif()
    if(NOT TARGET ${MODULE_NAME})
        message(WARNING "Unit> Skip '${MODULE_NAME}': target does not exist")
        return()
    endif()

    file(GLOB CASE_FILES "${CASE_DIR}/*.cpp")
    if(NOT CASE_FILES)
        return()
    endif()

    set(EXEC_NAME "test-units-${MODULE_NAME}")
    message("Unit> Build: ${EXEC_NAME}")

    get_target_property(MODULE_TYPE ${MODULE_NAME} TYPE)
    set(UNIT_SOURCES
            "${EOKAS_UNIT_ENGINE_DIR}/main.cpp"
            ${CASE_FILES}
    )

    set_property(GLOBAL PROPERTY EOKAS_UNIT_SEEN "")
    set_property(GLOBAL PROPERTY EOKAS_UNIT_LIBS "")
    set_property(GLOBAL PROPERTY EOKAS_UNIT_LIBDIRS "")
    set_property(GLOBAL PROPERTY EOKAS_UNIT_INCLUDES "")
    set_property(GLOBAL PROPERTY EOKAS_UNIT_DEFS "")

    if(MODULE_TYPE STREQUAL "EXECUTABLE")
        get_target_property(MODULE_SOURCES ${MODULE_NAME} SOURCES)
        foreach(src ${MODULE_SOURCES})
            if(NOT EXISTS "${src}")
                continue()
            endif()
            file(STRINGS "${src}" MAIN_HITS REGEX "^int[ \t]+main[ \t]*\\(")
            if(MAIN_HITS)
                message("Unit> Skip entry: ${src}")
                continue()
            endif()
            list(APPEND UNIT_SOURCES "${src}")
        endforeach()
    else()
        set_property(GLOBAL APPEND PROPERTY EOKAS_UNIT_LIBS "${MODULE_NAME}")
    endif()
    eokas_unit_walk(${MODULE_NAME})

    get_property(UNIT_LIBS GLOBAL PROPERTY EOKAS_UNIT_LIBS)
    get_property(UNIT_LIBDIRS GLOBAL PROPERTY EOKAS_UNIT_LIBDIRS)
    get_property(UNIT_INCLUDES GLOBAL PROPERTY EOKAS_UNIT_INCLUDES)
    get_property(UNIT_DEFS GLOBAL PROPERTY EOKAS_UNIT_DEFS)
    if(UNIT_LIBS)
        list(REMOVE_DUPLICATES UNIT_LIBS)
        # Static libraries are scanned once. Repeating the closure lets a
        # dependency that was pulled in early still satisfy later users.
        set(UNIT_LIBS_REPEAT ${UNIT_LIBS})
        list(APPEND UNIT_LIBS ${UNIT_LIBS_REPEAT})
    endif()

    add_executable(${EXEC_NAME} ${UNIT_SOURCES})
    target_include_directories(${EXEC_NAME} PRIVATE
            "${EOKAS_MODULES_DIR}"
            "${EOKAS_UNIT_ENGINE_DIR}"
            ${UNIT_INCLUDES}
    )
    if(UNIT_LIBDIRS)
        target_link_directories(${EXEC_NAME} PRIVATE ${UNIT_LIBDIRS})
    endif()
    if(UNIT_DEFS)
        target_compile_definitions(${EXEC_NAME} PRIVATE ${UNIT_DEFS})
    endif()
    if(UNIT_LIBS)
        target_link_libraries(${EXEC_NAME} PRIVATE ${UNIT_LIBS})
    endif()

    if(MODULE_NAME STREQUAL "ui" OR MODULE_NAME STREQUAL "imapp")
        target_sources(${EXEC_NAME} PRIVATE "${EOKAS_PROJECT_DIR}/test/test-ui/freetype_deps_stubs.cpp")
    endif()

    if(MODULE_NAME STREQUAL "fbx")
        file(GLOB FBX_DLLS "${EOKAS_MODULES_DIR}/fbx/fbxsdk/lib/x64/release/*.dll")
        foreach(dll ${FBX_DLLS})
            add_custom_command(TARGET ${EXEC_NAME} POST_BUILD
                    COMMAND ${CMAKE_COMMAND} -E copy_if_different
                    "${dll}" "$<TARGET_FILE_DIR:${EXEC_NAME}>")
        endforeach()
    endif()

    set(CASE_NAMES "")
    foreach(CASE_FILE ${CASE_FILES})
        file(STRINGS "${CASE_FILE}" CASE_LINES REGEX "EOKAS_TEST_CASE\\([A-Za-z_][A-Za-z0-9_]*\\)")
        foreach(LINE ${CASE_LINES})
            string(REGEX REPLACE ".*EOKAS_TEST_CASE\\(([A-Za-z_][A-Za-z0-9_]*)\\).*" "test_\\1" CASE_NAME "${LINE}")
            list(APPEND CASE_NAMES "${CASE_NAME}")
            message("Unit> Case: ${MODULE_NAME}.${CASE_NAME}")
        endforeach()
    endforeach()

    if(BUILD_TESTING)
        list(REMOVE_DUPLICATES CASE_NAMES)
        foreach(CASE_NAME ${CASE_NAMES})
            add_test(NAME "${MODULE_NAME}.${CASE_NAME}" COMMAND ${EXEC_NAME} ${CASE_NAME})
        endforeach()
    endif()
endfunction()

file(GLOB EOKAS_UNIT_MODULE_DIRS RELATIVE "${EOKAS_UNIT_CASES_DIR}" "${EOKAS_UNIT_CASES_DIR}/*")
foreach(MODULE_NAME ${EOKAS_UNIT_MODULE_DIRS})
    if(IS_DIRECTORY "${EOKAS_UNIT_CASES_DIR}/${MODULE_NAME}")
        eokas_add_unit_module(${MODULE_NAME})
    endif()
endforeach()
