#include "Unit.h"
#include "ui/main.h"

using namespace eokas;

EOKAS_TEST_CASE(ui) {
    int clicks = 0;
    UIWidget widget;
    widget.rect = Rect(0, 0, 40, 20);
    widget.onClick = [&]() { clicks += 1; };
    widget.triggerClick();
    EOKAS_EXPECT(clicks == 1);
    widget.triggerPointerEnter();
    EOKAS_EXPECT(widget.hovered);
    widget.triggerPointerLeave();
    EOKAS_EXPECT(!widget.hovered);

    UIList list;
    auto first = std::make_shared<UIWidget>();
    auto second = std::make_shared<UIWidget>();
    first->rect = Rect(0, 0, 10, 20);
    second->rect = Rect(0, 0, 10, 30);
    list.addChild(first);
    list.addChild(second);
    list.layout(Rect(0, 0, 100, 200));
    EOKAS_EXPECT(_FloatEqual(first->rect.origin.x, 8.0f));
    EOKAS_EXPECT(_FloatEqual(first->rect.origin.y, 8.0f));
    EOKAS_EXPECT(_FloatEqual(second->rect.origin.y, 36.0f));
    list.layout(Rect(40.0f, 70.0f, 100.0f, 200.0f));
    EOKAS_EXPECT(_FloatEqual(first->rect.origin.x, 8.0f));
    EOKAS_EXPECT(_FloatEqual(first->rect.origin.y, 8.0f));
    EOKAS_EXPECT(_FloatEqual(second->rect.origin.y, 36.0f));

    UIGrid grid;
    grid.columns = 2;
    grid.cellWidth = 16.0f;
    grid.cellHeight = 10.0f;
    auto cell = std::make_shared<UIWidget>();
    cell->rect = Rect(0, 0, 16, 10);
    grid.addChild(cell);
    grid.layout(Rect(0, 0, 80, 40));
    EOKAS_EXPECT(_FloatEqual(cell->rect.size.x, 16.0f));

    UITable table;
    table.border = UITableBorder(1.0f, Color(1, 1, 1, 1));
    table.cellSpacing = 8.0f;
    table.cellPadding = 4.0f;
    table.addColumn(40.0f);
    table.addColumn(0.0f);
    table.addRow(20.0f);
    table.addRow(0.0f);
    auto body = std::make_shared<UIWidget>();
    auto side = std::make_shared<UIWidget>();
    body->rect = Rect(0, 0, 12, 8);
    side->rect = Rect(0, 0, 10, 6);
    table.setContent(1, 0, body);
    table.setContent(0, 1, side);
    table.refit();
    EOKAS_EXPECT(_FloatEqual(table.rect.size.x, 68.0f));
    EOKAS_EXPECT(_FloatEqual(table.rect.size.y, 46.0f));
    table.layout(Rect(0, 0, 0, 0));
    EOKAS_EXPECT(_FloatEqual(body->rect.origin.x, 5.0f));
    EOKAS_EXPECT(_FloatEqual(body->rect.origin.y, 5.0f));
    table.layout(Rect(0, 0, 100, 0));
    EOKAS_EXPECT(_FloatEqual(table.cell(0, 1)->rect.origin.x, 48.0f));
    EOKAS_EXPECT(_FloatEqual(table.cell(0, 1)->rect.size.x, 52.0f));
    EOKAS_EXPECT(_FloatEqual(side->rect.origin.x, 5.0f));
    table.insertColumn(0, 10.0f);
    EOKAS_EXPECT(table.getContent(1, 1).get() == body.get());
    EOKAS_EXPECT(table.getContent(1, 0) == nullptr);
    table.removeRow(0);
    EOKAS_EXPECT(table.rowCount() == 1);
    EOKAS_EXPECT(table.getContent(0, 1).get() == body.get());
    EOKAS_EXPECT(table.cell(-1, 0) == nullptr);

    UITable tree;
    tree.border = UITableBorder(0.0f, Color(1, 1, 1, 1));
    tree.cellSpacing = 0.0f;
    tree.cellPadding = 0.0f;
    tree.addColumn(80.0f);
    tree.addColumn(40.0f);
    tree.setColumnIndent(0, -4.0f);
    EOKAS_EXPECT(_FloatEqual(tree.columnIndent(0), 0.0f));
    tree.setColumnIndent(0, 10.0f);
    UITableRow* group = tree.addRow(20.0f);
    UITableRow* child = group->addRow(20.0f);
    UITableRow* grand = child->addRow(20.0f);
    EOKAS_EXPECT(group->depth() == 0);
    EOKAS_EXPECT(child->parent() == group);
    EOKAS_EXPECT(child->depth() == 1);
    EOKAS_EXPECT(child->index() == 0);
    EOKAS_EXPECT(grand->depth() == 2);
    auto mark = std::make_shared<UIWidget>();
    auto other = std::make_shared<UIWidget>();
    mark->rect = Rect(0, 0, 12, 8);
    other->rect = Rect(0, 0, 6, 6);
    child->setContent(0, mark);
    child->setContent(1, other);
    tree.layout(Rect(0, 0, 0, 0));
    EOKAS_EXPECT(_FloatEqual(tree.rect.size.x, 120.0f));
    EOKAS_EXPECT(_FloatEqual(tree.rect.size.y, 60.0f));
    EOKAS_EXPECT(_FloatEqual(mark->rect.origin.x, 20.0f));
    EOKAS_EXPECT(_FloatEqual(mark->rect.origin.y, 0.0f));
    EOKAS_EXPECT(_FloatEqual(other->rect.origin.x, 0.0f));
    int leafHits = 0;
    grand->onExpandedChanged = [&](bool) { leafHits += 1; };
    grand->triggerClick();
    EOKAS_EXPECT(grand->expanded());
    EOKAS_EXPECT(leafHits == 0);
    child->setExpanded(false);
    EOKAS_EXPECT(!child->expanded());
    EOKAS_EXPECT(_FloatEqual(tree.rect.size.y, 40.0f));
    EOKAS_EXPECT(tree.children.size() == 2);
    child->setExpanded(true);
    group->setExpanded(false);
    EOKAS_EXPECT(child->expanded());
    EOKAS_EXPECT(_FloatEqual(tree.rect.size.y, 20.0f));
    EOKAS_EXPECT(tree.children.size() == 1);
    group->setExpanded(true);
    int hits = 0;
    group->onExpandedChanged = [&](bool) { hits += 1; };
    group->triggerClick();
    EOKAS_EXPECT(!group->expanded());
    EOKAS_EXPECT(hits == 1);
    group->setExpanded(true);
    tree.insertColumn(0, 8.0f);
    EOKAS_EXPECT(child->getContent(1).get() == mark.get());
    EOKAS_EXPECT(child->getContent(0) == nullptr);
    EOKAS_EXPECT(_FloatEqual(tree.columnIndent(0), 0.0f));
    EOKAS_EXPECT(_FloatEqual(tree.columnIndent(1), 10.0f));
    tree.removeRow(0);
    EOKAS_EXPECT(tree.rowCount() == 0);

    UITable wide;
    wide.border = UITableBorder(0.0f, Color(1, 1, 1, 1));
    wide.addColumn(0.0f);
    wide.setColumnIndent(0, 10.0f);
    UITableRow* only = wide.addRow(0.0f);
    auto box = std::make_shared<UIWidget>();
    box->rect = Rect(0, 0, 12, 8);
    only->setContent(0, box);
    wide.refit();
    EOKAS_EXPECT(_FloatEqual(wide.rect.size.x, 22.0f));
    EOKAS_EXPECT(_FloatEqual(wide.rect.size.y, 8.0f));

    UIButton button;
    button.setText("OK");
    EOKAS_EXPECT(button.label() != nullptr);
    EOKAS_EXPECT(button.label()->text == "OK");

    UIMenu menu;
    auto item = std::make_shared<UIMenuItem>();
    item->setText("File");
    menu.addItem(item);
    EOKAS_EXPECT(item->label() != nullptr);
    EOKAS_EXPECT(item->label()->text == "File");

    int expandedHits = 0;
    UIRegion region;
    region.onExpandedChanged = [&](bool expanded) { expandedHits += expanded ? 1 : -1; };
    region.setExpanded(false);
    EOKAS_EXPECT(!region.expanded());
    EOKAS_EXPECT(expandedHits == -1);

    UISlider slider;
    slider.setRange(0.0f, 10.0f);
    slider.setValue(12.0f);
    EOKAS_EXPECT(_FloatEqual(slider.value, 10.0f));

    int toggleHits = 0;
    UIToggle toggle;
    toggle.onValueChanged = [&](bool) { toggleHits += 1; };
    toggle.triggerClick();
    EOKAS_EXPECT(toggle.value);
    EOKAS_EXPECT(toggleHits == 1);

    UIInput input;
    input.setText("eokas");
    EOKAS_EXPECT(input.text == "eokas");
    EOKAS_EXPECT(input.acceptsKeyFocus());

    UIDropdown dropdown;
    dropdown.addItem(1, "One");
    dropdown.addItem(2, "Two");
    dropdown.setValue(2);
    EOKAS_EXPECT(dropdown.value == 2);
    EOKAS_EXPECT(dropdown.labelOf(2) == "Two");

    UIPrimitive primitive;
    primitive.begin();
    primitive.addQuad(Rect(0, 0, 10, 10), Rect(0, 0, 1, 1), Color(1, 1, 1, 1));
    primitive.end();
    EOKAS_EXPECT(primitive.indexCount == 6);
    EOKAS_EXPECT(primitive.vertexLength == 6 * sizeof(UIVertex));

    UIFrame frame;
    frame.init(200, 100);
    auto root = std::make_shared<UIWidget>();
    root->rect = Rect(0, 0, 200, 100);
    frame.setRoot(root);
    EOKAS_EXPECT(frame.hitTest(10, 10) == root.get());
    frame.onMouseDown(10, 10, 0);
    frame.onMouseUp(10, 10, 0);
    auto panel = std::make_shared<UIWidget>();
    panel->rect = Rect(50.0f, 60.0f, 80.0f, 40.0f);
    auto nested = std::make_shared<UIWidget>();
    nested->rect = Rect(10.0f, 8.0f, 20.0f, 12.0f);
    panel->children.push_back(nested);
    root->children.push_back(panel);
    EOKAS_EXPECT(frame.hitTest(62.0f, 70.0f) == nested.get());
    EOKAS_EXPECT(frame.hitTest(52.0f, 62.0f) == panel.get());
    frame.quit();

    UIView view;
    auto content = std::make_shared<UIWidget>();
    content->rect = Rect(0, 0, 400, 300);
    view.addChild(content);
    view.rect = Rect(0, 0, 50, 40);
    view.setScroll(4, 6);
    EOKAS_EXPECT(_FloatEqual(view.scrollX(), 4.0f));
    EOKAS_EXPECT(_FloatEqual(view.scrollY(), 6.0f));

    UIDockSpace dock;
    dock.layout(Rect(0, 0, 400, 300));
    auto page = std::make_shared<UIDockPage>();
    dock.dockPage(page, UIDockMode::Fill);
    dock.layout(Rect(0, 0, 400, 300));
    EOKAS_EXPECT(page->mode() == UIDockMode::Fill);
    EOKAS_EXPECT(page->space() == &dock);
    Rect bounds;
    EOKAS_EXPECT(dock.pageBounds(page.get(), bounds));
    EOKAS_EXPECT(bounds.size.x > 0.0f);
    EOKAS_EXPECT(bounds.size.y > 0.0f);

    int windows = 0;
    UIApp app;
    app.onCreateWindow = [&](const Rect&) {
        windows += 1;
        return (void*)1;
    };
    void* window = (void*)1;
    UIFrame& opened = app.open(window, 320, 240);
    EOKAS_EXPECT(app.find(window) == &opened);
    app.layout(window, 320, 240);
    app.close(window);
    EOKAS_EXPECT(app.find(window) == nullptr);

    UIWidget scaled;
    EOKAS_EXPECT(_FloatEqual(scaled.localScale.x, 1.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.localScale.y, 1.0f));
    scaled.localScale = Vector2(2.0f, 3.0f);
    scaled.layout(Rect(1.0f, 2.0f, 3.0f, 4.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.localScale.x, 2.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.localScale.y, 3.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.finalRect().origin.x, 1.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.finalRect().size.x, 6.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.finalRect().size.y, 12.0f));

    UIFrame scaleFrame;
    scaleFrame.init(200, 100);
    auto scaleRoot = std::make_shared<UIWidget>();
    scaleRoot->rect = Rect(0, 0, 200, 100);
    auto scaledBox = std::make_shared<UIWidget>();
    scaledBox->rect = Rect(10.0f, 10.0f, 20.0f, 20.0f);
    scaledBox->localScale = Vector2(2.0f, 2.0f);
    scaleRoot->children.push_back(scaledBox);
    scaleFrame.setRoot(scaleRoot);
    EOKAS_EXPECT(scaleFrame.hitTest(10.0f, 10.0f) == scaledBox.get());
    EOKAS_EXPECT(scaleFrame.hitTest(49.0f, 49.0f) == scaledBox.get());
    EOKAS_EXPECT(scaleFrame.hitTest(50.0f, 50.0f) == scaledBox.get());
    EOKAS_EXPECT(scaleFrame.hitTest(51.0f, 51.0f) == scaleRoot.get());
    EOKAS_EXPECT(scaleFrame.hitTest(9.0f, 10.0f) == scaleRoot.get());

    auto scaledParent = std::make_shared<UIWidget>();
    scaledParent->rect = Rect(0.0f, 0.0f, 100.0f, 40.0f);
    scaledParent->localScale = Vector2(2.0f, 1.0f);
    auto nestedScale = std::make_shared<UIWidget>();
    nestedScale->rect = Rect(10.0f, 0.0f, 10.0f, 10.0f);
    scaledParent->children.push_back(nestedScale);
    scaleRoot->children.clear();
    scaleRoot->children.push_back(scaledParent);
    EOKAS_EXPECT(scaleFrame.hitTest(20.0f, 0.0f) == nestedScale.get());
    EOKAS_EXPECT(scaleFrame.hitTest(19.0f, 0.0f) == scaledParent.get());
    scaleFrame.quit();

    UICanvas fitted;
    fitted.rect = Rect(100.0f, 50.0f, 0.0f, 0.0f);
    auto top = std::make_shared<UIWidget>();
    auto low = std::make_shared<UIWidget>();
    top->rect = Rect(0.0f, 0.0f, 10.0f, 20.0f);
    low->rect = Rect(30.0f, -5.0f, 10.0f, 10.0f);
    fitted.addChild(top);
    fitted.addChild(low);
    fitted.layout(fitted.rect);
    EOKAS_EXPECT(_FloatEqual(fitted.rect.origin.x, 100.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.rect.origin.y, 45.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.rect.size.x, 40.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.rect.size.y, 25.0f));
    EOKAS_EXPECT(_FloatEqual(top->rect.origin.y, 5.0f));
    EOKAS_EXPECT(_FloatEqual(low->rect.origin.y, 0.0f));
    top->rect.origin.x = -4.0f;
    fitted.refit();
    EOKAS_EXPECT(_FloatEqual(fitted.rect.origin.x, 96.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.rect.size.x, 44.0f));
    EOKAS_EXPECT(_FloatEqual(top->rect.origin.x, 0.0f));
    EOKAS_EXPECT(_FloatEqual(low->rect.origin.x, 34.0f));

    UICanvas scaledCanvas;
    scaledCanvas.localScale = Vector2(2.0f, 2.0f);
    scaledCanvas.rect = Rect(100.0f, 50.0f, 0.0f, 0.0f);
    auto leftItem = std::make_shared<UIWidget>();
    auto rightItem = std::make_shared<UIWidget>();
    leftItem->rect = Rect(0.0f, 0.0f, 10.0f, 20.0f);
    rightItem->rect = Rect(30.0f, -5.0f, 10.0f, 10.0f);
    scaledCanvas.addChild(leftItem);
    scaledCanvas.addChild(rightItem);
    scaledCanvas.layout(scaledCanvas.rect);
    leftItem->rect.origin.x = -4.0f;
    scaledCanvas.refit();
    EOKAS_EXPECT(_FloatEqual(scaledCanvas.rect.origin.x, 92.0f));
    EOKAS_EXPECT(_FloatEqual(scaledCanvas.rect.size.x, 44.0f));
    EOKAS_EXPECT(_FloatEqual(scaledCanvas.finalRect().size.x, 88.0f));
    EOKAS_EXPECT(_FloatEqual(leftItem->rect.origin.x, 0.0f));
    EOKAS_EXPECT(_FloatEqual(rightItem->rect.origin.x, 34.0f));

    UIFrame canvasFrame;
    canvasFrame.init(400, 300);
    auto canvas = std::make_shared<UICanvas>();
    canvas->rect = Rect(100.0f, 50.0f, 0.0f, 0.0f);
    auto held = std::make_shared<UIWidget>();
    auto loose = std::make_shared<UIWidget>();
    held->rect = Rect(0.0f, 0.0f, 10.0f, 20.0f);
    loose->rect = Rect(30.0f, -5.0f, 10.0f, 10.0f);
    loose->dragable = false;
    canvas->addChild(held);
    canvas->addChild(loose);
    canvasFrame.setRoot(canvas);
    canvasFrame.hitTest(0.0f, 0.0f);
    Rect heldBefore = held->rect;
    Rect looseBefore = loose->rect;
    canvasFrame.onMouseDown(120.0f, 65.0f, 0);
    canvasFrame.onMouseMove(130.0f, 70.0f);
    canvasFrame.onMouseUp(130.0f, 70.0f, 0);
    EOKAS_EXPECT(_FloatEqual(held->rect.origin.x, heldBefore.origin.x));
    EOKAS_EXPECT(_FloatEqual(held->rect.origin.y, heldBefore.origin.y));
    EOKAS_EXPECT(_FloatEqual(loose->rect.origin.x, looseBefore.origin.x));
    EOKAS_EXPECT(_FloatEqual(loose->rect.origin.y, looseBefore.origin.y));
    EOKAS_EXPECT(_FloatEqual(canvas->rect.origin.x, 110.0f));
    EOKAS_EXPECT(_FloatEqual(canvas->rect.origin.y, 50.0f));

    canvasFrame.onMouseDown(140.0f, 50.0f, 0);
    canvasFrame.onMouseMove(150.0f, 50.0f);
    canvasFrame.onMouseUp(150.0f, 50.0f, 0);
    EOKAS_EXPECT(_FloatEqual(loose->rect.origin.x, looseBefore.origin.x));
    loose->dragable = true;
    canvasFrame.onMouseDown(140.0f, 50.0f, 0);
    canvasFrame.onMouseMove(150.0f, 50.0f);
    canvasFrame.onMouseUp(150.0f, 50.0f, 0);
    EOKAS_EXPECT(_FloatEqual(loose->rect.origin.x, looseBefore.origin.x + 10.0f));
    EOKAS_EXPECT(_FloatEqual(held->rect.origin.x, heldBefore.origin.x));

    Vector2 pivot = canvas->rect.origin + Vector2(10.0f, 10.0f);
    Rect looseAtScale = loose->rect;
    canvasFrame.onMouseWheel(pivot.x, pivot.y, 0.0f, -48.0f);
    Vector2 delta = pivot - canvas->rect.origin;
    Vector2 under(delta.x / canvas->localScale.x, delta.y / canvas->localScale.y);
    Vector2 back = canvas->rect.origin + under * canvas->localScale;
    EOKAS_EXPECT(_FloatEqual(back.x, pivot.x));
    EOKAS_EXPECT(_FloatEqual(back.y, pivot.y));
    EOKAS_EXPECT(_FloatEqual(loose->rect.origin.x, looseAtScale.origin.x));
    EOKAS_EXPECT(_FloatEqual(loose->rect.origin.y, looseAtScale.origin.y));
    Vector2 fixedOrigin = canvas->rect.origin;
    canvas->scaleAt(canvas->rect.origin, canvas->localScale.x * 2.0f);
    EOKAS_EXPECT(_FloatEqual(canvas->rect.origin.x, fixedOrigin.x));
    EOKAS_EXPECT(_FloatEqual(canvas->rect.origin.y, fixedOrigin.y));

    auto dragButton = std::make_shared<UIButton>();
    dragButton->setText("OK");
    dragButton->rect = Rect(0.0f, 0.0f, 40.0f, 20.0f);
    dragButton->dragable = true;
    UICanvas dragGroup;
    dragGroup.addChild(dragButton);
    dragGroup.layout(Rect(0.0f, 0.0f, 0.0f, 0.0f));
    Rect labelRect = dragButton->label()->rect;
    dragGroup.dragChild(dragButton.get(), 5.0f, 6.0f);
    dragGroup.dragChild(dragButton.get(), 15.0f, 9.0f);
    EOKAS_EXPECT(_FloatEqual(dragGroup.rect.origin.x, 10.0f));
    EOKAS_EXPECT(_FloatEqual(dragGroup.rect.origin.y, 3.0f));
    EOKAS_EXPECT(_FloatEqual(dragButton->rect.origin.x, 0.0f));
    EOKAS_EXPECT(_FloatEqual(dragButton->rect.origin.y, 0.0f));
    EOKAS_EXPECT(_FloatEqual(dragButton->label()->rect.origin.x, labelRect.origin.x));
    EOKAS_EXPECT(_FloatEqual(dragButton->label()->rect.origin.y, labelRect.origin.y));

    UIChart triangle;
    triangle.setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    EOKAS_EXPECT(triangle.contains(Vector2(5.0f, 5.0f)));
    EOKAS_EXPECT(!triangle.contains(Vector2(30.0f, 30.0f)));

    UIFrame shapeFrame;
    shapeFrame.init(200, 200);
    auto shapeRoot = std::make_shared<UIWidget>();
    shapeRoot->rect = Rect(0.0f, 0.0f, 200.0f, 200.0f);
    shapeRoot->interactive = false;
    auto lowerChart = std::make_shared<UIChart>();
    auto upperChart = std::make_shared<UIChart>();
    lowerChart->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(40.0f, 40.0f), Vector2(0.0f, 40.0f) });
    upperChart->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    shapeRoot->children.push_back(lowerChart);
    shapeRoot->children.push_back(upperChart);
    shapeFrame.setRoot(shapeRoot);
    EOKAS_EXPECT(shapeFrame.hitTest(5.0f, 5.0f) == upperChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(30.0f, 5.0f) == upperChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(30.0f, 30.0f) == lowerChart.get());

    auto parentChart = std::make_shared<UIChart>();
    parentChart->setContour({ Vector2(0.0f, 0.0f), Vector2(80.0f, 0.0f), Vector2(0.0f, 80.0f) });
    auto innerChart = std::make_shared<UIChart>();
    innerChart->setContour({ Vector2(4.0f, 4.0f), Vector2(16.0f, 4.0f), Vector2(4.0f, 16.0f) });
    auto outerChart = std::make_shared<UIChart>();
    outerChart->setContour({ Vector2(50.0f, 50.0f), Vector2(70.0f, 50.0f), Vector2(50.0f, 70.0f) });
    parentChart->addChart(innerChart);
    parentChart->addChart(outerChart);
    shapeRoot->children.clear();
    shapeRoot->children.push_back(parentChart);
    EOKAS_EXPECT(shapeFrame.hitTest(6.0f, 6.0f) == innerChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(2.0f, 2.0f) == parentChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(55.0f, 55.0f) == nullptr);
    parentChart->interactive = false;
    EOKAS_EXPECT(shapeFrame.hitTest(2.0f, 2.0f) == nullptr);
    shapeFrame.quit();

    UIFrame chartFrame;
    chartFrame.init(300, 200);
    auto chartCanvas = std::make_shared<UICanvas>();
    chartCanvas->rect = Rect(0.0f, 0.0f, 300.0f, 200.0f);
    auto anchor = std::make_shared<UIWidget>();
    anchor->rect = Rect(0.0f, 0.0f, 8.0f, 8.0f);
    anchor->interactive = false;
    auto picked = std::make_shared<UIChart>();
    auto idle = std::make_shared<UIChart>();
    picked->setContour({ Vector2(20.0f, 20.0f), Vector2(60.0f, 20.0f), Vector2(20.0f, 60.0f) });
    idle->setContour({ Vector2(70.0f, 20.0f), Vector2(110.0f, 20.0f), Vector2(70.0f, 60.0f) });
    chartCanvas->addChild(anchor);
    chartCanvas->addChild(picked);
    chartCanvas->addChild(idle);
    chartFrame.setRoot(chartCanvas);
    int chartClicks = 0;
    int chartDoubles = 0;
    picked->onClick = [&]() { chartClicks += 1; };
    picked->onDoubleClick = [&]() { chartDoubles += 1; };
    chartFrame.onMouseDown(30.0f, 30.0f, 0);
    chartFrame.onMouseUp(30.0f, 30.0f, 0);
    EOKAS_EXPECT(chartClicks == 1);
    EOKAS_EXPECT(picked->selected);
    EOKAS_EXPECT(!idle->selected);
    picked->triggerClick();
    EOKAS_EXPECT(chartDoubles == 1);

    std::vector<Vector2> contourBefore = picked->contour();
    picked->selected = true;
    idle->selected = false;
    chartFrame.onMouseDown(30.0f, 30.0f, 0);
    chartFrame.onMouseMove(42.0f, 30.0f);
    chartFrame.onMouseUp(42.0f, 30.0f, 0);
    EOKAS_EXPECT(chartClicks == 2);
    EOKAS_EXPECT(picked->selected);
    EOKAS_EXPECT(!idle->selected);
    EOKAS_EXPECT(_FloatEqual(picked->rect.origin.x, contourBefore.empty() ? 0.0f : 32.0f));
    EOKAS_EXPECT(picked->contour().size() == contourBefore.size());
    EOKAS_EXPECT(_FloatEqual(picked->contour()[0].x, contourBefore[0].x));
    EOKAS_EXPECT(_FloatEqual(picked->contour()[0].y, contourBefore[0].y));
    chartFrame.quit();

    UIFrame dropFrame;
    dropFrame.init(300, 120);
    auto dropCanvas = std::make_shared<UICanvas>();
    dropCanvas->rect = Rect(0.0f, 0.0f, 300.0f, 120.0f);
    auto carried = std::make_shared<UIChart>();
    auto slot = std::make_shared<UIChart>();
    carried->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    slot->setContour({ Vector2(80.0f, 0.0f), Vector2(120.0f, 0.0f), Vector2(80.0f, 40.0f) });
    dropCanvas->addChild(carried);
    dropCanvas->addChild(slot);
    dropFrame.setRoot(dropCanvas);
    int drops = 0;
    UIChart* dropTarget = nullptr;
    carried->onDrop = [&](UIChart* target, float, float) {
        drops += 1;
        dropTarget = target;
    };
    dropFrame.onMouseDown(10.0f, 10.0f, 0);
    dropFrame.onMouseMove(90.0f, 10.0f);
    dropFrame.onMouseUp(90.0f, 10.0f, 0);
    EOKAS_EXPECT(drops == 1);
    EOKAS_EXPECT(dropTarget == slot.get());

    auto plainCanvas = std::make_shared<UICanvas>();
    plainCanvas->rect = Rect(0.0f, 0.0f, 300.0f, 120.0f);
    auto stone = std::make_shared<UIChart>();
    stone->setContour({ Vector2(60.0f, 0.0f), Vector2(100.0f, 0.0f), Vector2(60.0f, 40.0f) });
    auto plain = std::make_shared<UIWidget>();
    plain->rect = Rect(0.0f, 0.0f, 40.0f, 40.0f);
    plainCanvas->addChild(stone);
    plainCanvas->addChild(plain);
    dropFrame.setRoot(plainCanvas);
    int plainDrops = 0;
    UIChart* plainTarget = stone.get();
    stone->onDrop = [&](UIChart* target, float, float) {
        plainDrops += 1;
        plainTarget = target;
    };
    dropFrame.onMouseDown(70.0f, 10.0f, 0);
    dropFrame.onMouseMove(10.0f, 10.0f);
    dropFrame.onMouseUp(10.0f, 10.0f, 0);
    EOKAS_EXPECT(plainDrops == 1);
    EOKAS_EXPECT(plainTarget == nullptr);
    dropFrame.quit();

    UIFrame zoomFrame;
    zoomFrame.init(200, 200);
    auto zoomCanvas = std::make_shared<UICanvas>();
    zoomCanvas->rect = Rect(0.0f, 0.0f, 200.0f, 200.0f);
    auto zoomChart = std::make_shared<UIChart>();
    zoomChart->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    zoomCanvas->addChild(zoomChart);
    zoomFrame.setRoot(zoomCanvas);
    zoomFrame.onMouseWheel(10.0f, 10.0f, 0.0f, -48.0f);
    EOKAS_EXPECT(zoomChart->localScale.x > 1.0f);
    EOKAS_EXPECT(_FloatEqual(zoomCanvas->localScale.x, 1.0f));
    Vector2 zoomPivot(10.0f, 10.0f);
    Vector2 fromPivot = zoomPivot - zoomChart->rect.origin;
    Vector2 zoomUnder(fromPivot.x / zoomChart->localScale.x, fromPivot.y / zoomChart->localScale.y);
    Vector2 zoomBack = zoomChart->rect.origin + zoomUnder * zoomChart->localScale;
    EOKAS_EXPECT(_FloatEqual(zoomBack.x, zoomPivot.x));
    EOKAS_EXPECT(_FloatEqual(zoomBack.y, zoomPivot.y));
    zoomFrame.onMouseWheel(180.0f, 180.0f, 0.0f, -48.0f);
    EOKAS_EXPECT(zoomCanvas->localScale.x > 1.0f);
    zoomFrame.quit();

    UIEllipse ellipse;
    ellipse.rect = Rect(0.0f, 0.0f, 40.0f, 20.0f);
    EOKAS_EXPECT(ellipse.contains(Vector2(20.0f, 10.0f)));
    EOKAS_EXPECT(ellipse.contains(Vector2(40.0f, 10.0f)));
    EOKAS_EXPECT(!ellipse.contains(Vector2(0.0f, 0.0f)));
    EOKAS_EXPECT(_FloatEqual(ellipse.rect.size.x, 40.0f));
    EOKAS_EXPECT(_FloatEqual(ellipse.rect.size.y, 20.0f));
    UIPrimitive ellipsePrimitive;
    ellipsePrimitive.begin();
    ellipse.render(ellipsePrimitive);
    ellipsePrimitive.end();
    uint32_t fillCount = ellipsePrimitive.indexCount;
    ellipse.stroke.thickness = 2.0f;
    ellipse.selected = true;
    ellipsePrimitive.begin();
    ellipse.render(ellipsePrimitive);
    ellipsePrimitive.end();
    EOKAS_EXPECT(ellipsePrimitive.indexCount > fillCount);

    UIRectangle chartBox;
    chartBox.rect = Rect(10.0f, 20.0f, 40.0f, 20.0f);
    EOKAS_EXPECT(chartBox.contains(Vector2(10.0f, 20.0f)));
    EOKAS_EXPECT(chartBox.contains(Vector2(30.0f, 30.0f)));
    EOKAS_EXPECT(chartBox.contains(Vector2(50.0f, 40.0f)));
    EOKAS_EXPECT(!chartBox.contains(Vector2(9.0f, 30.0f)));

    UIDiamond diamond;
    diamond.rect = Rect(0.0f, 0.0f, 40.0f, 20.0f);
    EOKAS_EXPECT(diamond.contains(Vector2(20.0f, 10.0f)));
    EOKAS_EXPECT(diamond.contains(Vector2(20.0f, 0.0f)));
    EOKAS_EXPECT(diamond.contains(Vector2(40.0f, 10.0f)));
    EOKAS_EXPECT(!diamond.contains(Vector2(0.0f, 0.0f)));
    EOKAS_EXPECT(!diamond.contains(Vector2(40.0f, 0.0f)));

    auto from = std::make_shared<UIRectangle>();
    auto to = std::make_shared<UIRectangle>();
    from->rect = Rect(0.0f, 0.0f, 40.0f, 20.0f);
    to->rect = Rect(80.0f, 0.0f, 40.0f, 20.0f);
    UILink link;
    link.kind = UIPathKind::Straight;
    link.setPoints({ Vector2(40.0f, 10.0f), Vector2(80.0f, 10.0f) });
    link.line.thickness = 2.0f;
    link.hitSlop = 4.0f;
    EOKAS_EXPECT(link.contains(Vector2(60.0f, 10.0f)));
    EOKAS_EXPECT(!link.contains(Vector2(60.0f, 30.0f)));
    link.start.target = from.get();
    link.start.anchor = UIAnchor::Right;
    link.end.target = to.get();
    link.end.anchor = UIAnchor::Left;
    EOKAS_EXPECT(link.contains(Vector2(60.0f, 10.0f)));
    to->rect.origin = Vector2(80.0f, 40.0f);
    EOKAS_EXPECT(link.contains(Vector2(60.0f, 30.0f)));
    EOKAS_EXPECT(!link.contains(Vector2(60.0f, 10.0f)));

    from->rect = Rect(0.0f, 0.0f, 40.0f, 20.0f);
    to->rect = Rect(80.0f, 40.0f, 40.0f, 20.0f);
    UILink curve;
    curve.kind = UIPathKind::CubicBezier;
    curve.setPoints({
        Vector2(40.0f, 10.0f),
        Vector2(50.0f, -40.0f),
        Vector2(70.0f, 80.0f),
        Vector2(80.0f, 10.0f)
    });
    curve.line.thickness = 2.0f;
    curve.hitSlop = 3.0f;
    curve.start.target = from.get();
    curve.start.anchor = UIAnchor::Right;
    curve.end.target = to.get();
    curve.end.anchor = UIAnchor::Left;
    EOKAS_EXPECT(curve.contains(Vector2(44.0f, 10.0f)));
    EOKAS_EXPECT(curve.contains(Vector2(76.0f, 50.0f)));
    EOKAS_EXPECT(!curve.contains(Vector2(48.0f, -20.0f)));

    UIRectangle cornerBox;
    cornerBox.rect = Rect(0.0f, 0.0f, 40.0f, 20.0f);
    cornerBox.border.thickness = 2.0f;
    UIPrimitive cornerPrimitive;
    cornerPrimitive.begin();
    cornerBox.render(cornerPrimitive);
    cornerPrimitive.end();
    EOKAS_EXPECT(cornerPrimitive.indexCount == 54);

    canvasFrame.quit();
    return 0;
}
