#include "Unit.h"
#include "ui/main.h"
#include <cmath>

using namespace eokas;

EOKAS_TEST_CASE(ui) {
    int clicks = 0;
    UIWidget widget;
    widget.shape.size = (Rect(0, 0, 40, 20)).size;
    widget.shape.origin = (Rect(0, 0, 40, 20)).origin + widget.shape.pivot * widget.shape.size;
    widget.onClick = [&]() { clicks += 1; };
    widget.triggerClick();
    EOKAS_EXPECT(clicks == 1);
    widget.triggerPointerEnter();
    EOKAS_EXPECT(widget.hovered);
    widget.triggerPointerLeave();
    EOKAS_EXPECT(!widget.hovered);

    UIList list;
    auto first = std::make_shared<UIWidget>();
    auto second = std::make_shared<UIWidget>();
    first->shape.size = (Rect(0, 0, 10, 20)).size;
    first->shape.origin = (Rect(0, 0, 10, 20)).origin + first->shape.pivot * first->shape.size;
    second->shape.size = (Rect(0, 0, 10, 30)).size;
    second->shape.origin = (Rect(0, 0, 10, 30)).origin + second->shape.pivot * second->shape.size;
    list.addChild(first);
    list.addChild(second);
    list.layout(Rect(0, 0, 100, 200));
    EOKAS_EXPECT(_FloatEqual(first->shape.left(), 8.0f));
    EOKAS_EXPECT(_FloatEqual(first->shape.top(), 8.0f));
    EOKAS_EXPECT(_FloatEqual(second->shape.top(), 36.0f));
    list.layout(Rect(40.0f, 70.0f, 100.0f, 200.0f));
    EOKAS_EXPECT(_FloatEqual(first->shape.left(), 8.0f));
    EOKAS_EXPECT(_FloatEqual(first->shape.top(), 8.0f));
    EOKAS_EXPECT(_FloatEqual(second->shape.top(), 36.0f));

    UIGrid grid;
    grid.columns = 2;
    grid.cellWidth = 16.0f;
    grid.cellHeight = 10.0f;
    auto cell = std::make_shared<UIWidget>();
    cell->shape.size = (Rect(0, 0, 16, 10)).size;
    cell->shape.origin = (Rect(0, 0, 16, 10)).origin + cell->shape.pivot * cell->shape.size;
    grid.addChild(cell);
    grid.layout(Rect(0, 0, 80, 40));
    EOKAS_EXPECT(_FloatEqual(cell->shape.size.x, 16.0f));

    UITable table;
    table.border = UITableBorder(1.0f, Color(1, 1, 1, 1));
    table.cellSpacing = 8.0f;
    table.cellPadding = 4.0f;
    table.addColumn(40.0f);
    table.addColumn(0.0f);
    table.addRow(20.0f);
    table.addRow(0.0f);
    auto body = std::make_shared<UIWidget>();
    auto side = std::make_shared<UIWidget>();
    body->shape.size = (Rect(0, 0, 12, 8)).size;
    body->shape.origin = (Rect(0, 0, 12, 8)).origin + body->shape.pivot * body->shape.size;
    side->shape.size = (Rect(0, 0, 10, 6)).size;
    side->shape.origin = (Rect(0, 0, 10, 6)).origin + side->shape.pivot * side->shape.size;
    table.setContent(1, 0, body);
    table.setContent(0, 1, side);
    table.refit();
    EOKAS_EXPECT(_FloatEqual(table.shape.size.x, 68.0f));
    EOKAS_EXPECT(_FloatEqual(table.shape.size.y, 46.0f));
    table.layout(Rect(0, 0, 0, 0));
    EOKAS_EXPECT(_FloatEqual(body->shape.left(), 5.0f));
    EOKAS_EXPECT(_FloatEqual(body->shape.top(), 5.0f));
    table.layout(Rect(0, 0, 100, 0));
    EOKAS_EXPECT(_FloatEqual(table.cell(0, 1)->shape.left(), 48.0f));
    EOKAS_EXPECT(_FloatEqual(table.cell(0, 1)->shape.size.x, 52.0f));
    EOKAS_EXPECT(_FloatEqual(side->shape.left(), 5.0f));
    table.insertColumn(0, 10.0f);
    EOKAS_EXPECT(table.getContent(1, 1).get() == body.get());
    EOKAS_EXPECT(table.getContent(1, 0) == nullptr);
    table.removeRow(0);
    EOKAS_EXPECT(table.rowCount() == 1);
    EOKAS_EXPECT(table.getContent(0, 1).get() == body.get());
    EOKAS_EXPECT(table.cell(-1, 0) == nullptr);

    UITable tree;
    tree.border = UITableBorder(0.0f, Color(1, 1, 1, 1));
    tree.cellSpacing = 0.0f;
    tree.cellPadding = 0.0f;
    tree.addColumn(80.0f);
    tree.addColumn(40.0f);
    tree.setColumnIndent(0, -4.0f);
    EOKAS_EXPECT(_FloatEqual(tree.columnIndent(0), 0.0f));
    tree.setColumnIndent(0, 10.0f);
    UITableRow* group = tree.addRow(20.0f);
    UITableRow* child = group->addRow(20.0f);
    UITableRow* grand = child->addRow(20.0f);
    EOKAS_EXPECT(group->depth() == 0);
    EOKAS_EXPECT(child->parent() == group);
    EOKAS_EXPECT(child->depth() == 1);
    EOKAS_EXPECT(child->index() == 0);
    EOKAS_EXPECT(grand->depth() == 2);
    auto mark = std::make_shared<UIWidget>();
    auto other = std::make_shared<UIWidget>();
    mark->shape.size = (Rect(0, 0, 12, 8)).size;
    mark->shape.origin = (Rect(0, 0, 12, 8)).origin + mark->shape.pivot * mark->shape.size;
    other->shape.size = (Rect(0, 0, 6, 6)).size;
    other->shape.origin = (Rect(0, 0, 6, 6)).origin + other->shape.pivot * other->shape.size;
    child->setContent(0, mark);
    child->setContent(1, other);
    tree.layout(Rect(0, 0, 0, 0));
    EOKAS_EXPECT(_FloatEqual(tree.shape.size.x, 120.0f));
    EOKAS_EXPECT(_FloatEqual(tree.shape.size.y, 60.0f));
    EOKAS_EXPECT(_FloatEqual(mark->shape.left(), 20.0f));
    EOKAS_EXPECT(_FloatEqual(mark->shape.top(), 0.0f));
    EOKAS_EXPECT(_FloatEqual(other->shape.left(), 0.0f));
    int leafHits = 0;
    grand->onExpandedChanged = [&](bool) { leafHits += 1; };
    grand->triggerClick();
    EOKAS_EXPECT(grand->expanded());
    EOKAS_EXPECT(leafHits == 0);
    child->setExpanded(false);
    EOKAS_EXPECT(!child->expanded());
    EOKAS_EXPECT(_FloatEqual(tree.shape.size.y, 40.0f));
    EOKAS_EXPECT(tree.children.size() == 2);
    child->setExpanded(true);
    group->setExpanded(false);
    EOKAS_EXPECT(child->expanded());
    EOKAS_EXPECT(_FloatEqual(tree.shape.size.y, 20.0f));
    EOKAS_EXPECT(tree.children.size() == 1);
    group->setExpanded(true);
    int hits = 0;
    group->onExpandedChanged = [&](bool) { hits += 1; };
    group->triggerClick();
    EOKAS_EXPECT(!group->expanded());
    EOKAS_EXPECT(hits == 1);
    group->setExpanded(true);
    tree.insertColumn(0, 8.0f);
    EOKAS_EXPECT(child->getContent(1).get() == mark.get());
    EOKAS_EXPECT(child->getContent(0) == nullptr);
    EOKAS_EXPECT(_FloatEqual(tree.columnIndent(0), 0.0f));
    EOKAS_EXPECT(_FloatEqual(tree.columnIndent(1), 10.0f));
    tree.removeRow(0);
    EOKAS_EXPECT(tree.rowCount() == 0);

    UITable wide;
    wide.border = UITableBorder(0.0f, Color(1, 1, 1, 1));
    wide.addColumn(0.0f);
    wide.setColumnIndent(0, 10.0f);
    UITableRow* only = wide.addRow(0.0f);
    auto box = std::make_shared<UIWidget>();
    box->shape.size = (Rect(0, 0, 12, 8)).size;
    box->shape.origin = (Rect(0, 0, 12, 8)).origin + box->shape.pivot * box->shape.size;
    only->setContent(0, box);
    wide.refit();
    EOKAS_EXPECT(_FloatEqual(wide.shape.size.x, 22.0f));
    EOKAS_EXPECT(_FloatEqual(wide.shape.size.y, 8.0f));

    UIButton button;
    button.setText("OK");
    EOKAS_EXPECT(button.label() != nullptr);
    EOKAS_EXPECT(button.label()->text == "OK");

    UIMenu menu;
    auto item = std::make_shared<UIMenuItem>();
    item->setText("File");
    menu.addItem(item);
    EOKAS_EXPECT(item->label() != nullptr);
    EOKAS_EXPECT(item->label()->text == "File");

    int expandedHits = 0;
    UIRegion region;
    region.onExpandedChanged = [&](bool expanded) { expandedHits += expanded ? 1 : -1; };
    region.setExpanded(false);
    EOKAS_EXPECT(!region.expanded());
    EOKAS_EXPECT(expandedHits == -1);

    UISlider slider;
    slider.setRange(0.0f, 10.0f);
    slider.setValue(12.0f);
    EOKAS_EXPECT(_FloatEqual(slider.value, 10.0f));

    int toggleHits = 0;
    UIToggle toggle;
    toggle.onValueChanged = [&](bool) { toggleHits += 1; };
    toggle.triggerClick();
    EOKAS_EXPECT(toggle.value);
    EOKAS_EXPECT(toggleHits == 1);

    UIInput input;
    input.setText("eokas");
    EOKAS_EXPECT(input.text == "eokas");
    EOKAS_EXPECT(input.acceptsKeyFocus());

    UIDropdown dropdown;
    dropdown.addItem(1, "One");
    dropdown.addItem(2, "Two");
    dropdown.setValue(2);
    EOKAS_EXPECT(dropdown.value == 2);
    EOKAS_EXPECT(dropdown.labelOf(2) == "Two");

    UIPrimitive primitive;
    primitive.begin();
    primitive.addQuad(Rect(0, 0, 10, 10), Rect(0, 0, 1, 1), Color(1, 1, 1, 1));
    primitive.end();
    EOKAS_EXPECT(primitive.indexCount == 6);
    EOKAS_EXPECT(primitive.vertexLength == 6 * sizeof(UIVertex));

    UIFrame frame;
    frame.init(200, 100);
    auto root = std::make_shared<UIWidget>();
    root->shape.size = (Rect(0, 0, 200, 100)).size;
    root->shape.origin = (Rect(0, 0, 200, 100)).origin + root->shape.pivot * root->shape.size;
    frame.setRoot(root);
    EOKAS_EXPECT(frame.hitTest(10, 10) == root.get());
    frame.onMouseDown(10, 10, 0);
    frame.onMouseUp(10, 10, 0);
    auto panel = std::make_shared<UIWidget>();
    panel->shape.size = (Rect(50.0f, 60.0f, 80.0f, 40.0f)).size;
    panel->shape.origin = (Rect(50.0f, 60.0f, 80.0f, 40.0f)).origin + panel->shape.pivot * panel->shape.size;
    auto nested = std::make_shared<UIWidget>();
    nested->shape.size = (Rect(10.0f, 8.0f, 20.0f, 12.0f)).size;
    nested->shape.origin = (Rect(10.0f, 8.0f, 20.0f, 12.0f)).origin + nested->shape.pivot * nested->shape.size;
    panel->children.push_back(nested);
    root->children.push_back(panel);
    EOKAS_EXPECT(frame.hitTest(62.0f, 70.0f) == nested.get());
    EOKAS_EXPECT(frame.hitTest(52.0f, 62.0f) == panel.get());
    frame.quit();

    UIView view;
    auto content = std::make_shared<UIWidget>();
    content->shape.size = (Rect(0, 0, 400, 300)).size;
    content->shape.origin = (Rect(0, 0, 400, 300)).origin + content->shape.pivot * content->shape.size;
    view.addChild(content);
    view.shape.size = (Rect(0, 0, 50, 40)).size;
    view.shape.origin = (Rect(0, 0, 50, 40)).origin + view.shape.pivot * view.shape.size;
    view.setScroll(4, 6);
    EOKAS_EXPECT(_FloatEqual(view.scrollX(), 4.0f));
    EOKAS_EXPECT(_FloatEqual(view.scrollY(), 6.0f));

    UIDockSpace dock;
    dock.layout(Rect(0, 0, 400, 300));
    auto page = std::make_shared<UIDockPage>();
    dock.dockPage(page, UIDockMode::Fill);
    dock.layout(Rect(0, 0, 400, 300));
    EOKAS_EXPECT(page->mode() == UIDockMode::Fill);
    EOKAS_EXPECT(page->space() == &dock);
    Rect bounds;
    EOKAS_EXPECT(dock.pageBounds(page.get(), bounds));
    EOKAS_EXPECT(bounds.size.x > 0.0f);
    EOKAS_EXPECT(bounds.size.y > 0.0f);

    int windows = 0;
    UIApp app;
    app.onCreateWindow = [&](const Rect&) {
        windows += 1;
        return (void*)1;
    };
    void* window = (void*)1;
    UIFrame& opened = app.open(window, 320, 240);
    EOKAS_EXPECT(app.find(window) == &opened);
    app.layout(window, 320, 240);
    app.close(window);
    EOKAS_EXPECT(app.find(window) == nullptr);

    UIWidget scaled;
    EOKAS_EXPECT(_FloatEqual(scaled.shape.scale.x, 1.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.shape.scale.y, 1.0f));
    scaled.shape.scale = Vector2(2.0f, 3.0f);
    scaled.layout(Rect(1.0f, 2.0f, 3.0f, 4.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.shape.scale.x, 2.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.shape.scale.y, 3.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.shape.origin.x, 2.5f));
    EOKAS_EXPECT(_FloatEqual(scaled.shape.origin.y, 4.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.visualRect().origin.x, -0.5f));
    EOKAS_EXPECT(_FloatEqual(scaled.visualRect().origin.y, -2.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.visualRect().size.x, 6.0f));
    EOKAS_EXPECT(_FloatEqual(scaled.visualRect().size.y, 12.0f));

    UIFrame scaleFrame;
    scaleFrame.init(200, 100);
    auto scaleRoot = std::make_shared<UIWidget>();
    scaleRoot->shape.size = (Rect(0, 0, 200, 100)).size;
    scaleRoot->shape.origin = (Rect(0, 0, 200, 100)).origin + scaleRoot->shape.pivot * scaleRoot->shape.size;
    auto scaledBox = std::make_shared<UIWidget>();
    scaledBox->shape.size = (Rect(10.0f, 10.0f, 20.0f, 20.0f)).size;
    scaledBox->shape.origin = (Rect(10.0f, 10.0f, 20.0f, 20.0f)).origin + scaledBox->shape.pivot * scaledBox->shape.size;
    scaledBox->shape.scale = Vector2(2.0f, 2.0f);
    scaleRoot->children.push_back(scaledBox);
    scaleFrame.setRoot(scaleRoot);
    EOKAS_EXPECT(scaleFrame.hitTest(0.0f, 0.0f) == scaledBox.get());
    EOKAS_EXPECT(scaleFrame.hitTest(40.0f, 40.0f) == scaledBox.get());
    EOKAS_EXPECT(scaleFrame.hitTest(41.0f, 41.0f) == scaleRoot.get());

    auto scaledParent = std::make_shared<UIWidget>();
    scaledParent->shape.size = (Rect(0.0f, 0.0f, 100.0f, 40.0f)).size;
    scaledParent->shape.origin = (Rect(0.0f, 0.0f, 100.0f, 40.0f)).origin + scaledParent->shape.pivot * scaledParent->shape.size;
    scaledParent->shape.scale = Vector2(2.0f, 1.0f);
    auto nestedScale = std::make_shared<UIWidget>();
    nestedScale->shape.size = (Rect(10.0f, 0.0f, 10.0f, 10.0f)).size;
    nestedScale->shape.origin = (Rect(10.0f, 0.0f, 10.0f, 10.0f)).origin + nestedScale->shape.pivot * nestedScale->shape.size;
    scaledParent->children.push_back(nestedScale);
    scaleRoot->children.clear();
    scaleRoot->children.push_back(scaledParent);
    EOKAS_EXPECT(scaleFrame.hitTest(-30.0f, 0.0f) == nestedScale.get());
    EOKAS_EXPECT(scaleFrame.hitTest(-10.0f, 0.0f) == nestedScale.get());
    EOKAS_EXPECT(scaleFrame.hitTest(-31.0f, 0.0f) == scaledParent.get());
    EOKAS_EXPECT(scaleFrame.hitTest(20.0f, 0.0f) == scaledParent.get());
    scaleFrame.quit();

    UICanvas fitted;
    fitted.shape.size = (Rect(100.0f, 50.0f, 0.0f, 0.0f)).size;
    fitted.shape.origin = (Rect(100.0f, 50.0f, 0.0f, 0.0f)).origin + fitted.shape.pivot * fitted.shape.size;
    auto top = std::make_shared<UIWidget>();
    auto low = std::make_shared<UIWidget>();
    top->shape.size = (Rect(0.0f, 0.0f, 10.0f, 20.0f)).size;
    top->shape.origin = (Rect(0.0f, 0.0f, 10.0f, 20.0f)).origin + top->shape.pivot * top->shape.size;
    low->shape.size = (Rect(30.0f, -5.0f, 10.0f, 10.0f)).size;
    low->shape.origin = (Rect(30.0f, -5.0f, 10.0f, 10.0f)).origin + low->shape.pivot * low->shape.size;
    fitted.addChild(top);
    fitted.addChild(low);
    fitted.layout(Rect(fitted.shape.left(), fitted.shape.top(), fitted.shape.size.x, fitted.shape.size.y));
    EOKAS_EXPECT(_FloatEqual(fitted.shape.left(), 100.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.shape.top(), 45.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.shape.size.x, 40.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.shape.size.y, 25.0f));
    EOKAS_EXPECT(_FloatEqual(top->shape.top(), 5.0f));
    EOKAS_EXPECT(_FloatEqual(low->shape.top(), 0.0f));
    top->shape.origin.x = (-4.0f) + top->shape.pivot.x * top->shape.size.x;
    fitted.refit();
    EOKAS_EXPECT(_FloatEqual(fitted.shape.left(), 96.0f));
    EOKAS_EXPECT(_FloatEqual(fitted.shape.size.x, 44.0f));
    EOKAS_EXPECT(_FloatEqual(top->shape.left(), 0.0f));
    EOKAS_EXPECT(_FloatEqual(low->shape.left(), 34.0f));

    UICanvas scaledCanvas;
    scaledCanvas.shape.scale = Vector2(2.0f, 2.0f);
    scaledCanvas.shape.size = (Rect(100.0f, 50.0f, 0.0f, 0.0f)).size;
    scaledCanvas.shape.origin = (Rect(100.0f, 50.0f, 0.0f, 0.0f)).origin + scaledCanvas.shape.pivot * scaledCanvas.shape.size;
    auto leftItem = std::make_shared<UIWidget>();
    auto rightItem = std::make_shared<UIWidget>();
    leftItem->shape.size = (Rect(0.0f, 0.0f, 10.0f, 20.0f)).size;
    leftItem->shape.origin = (Rect(0.0f, 0.0f, 10.0f, 20.0f)).origin + leftItem->shape.pivot * leftItem->shape.size;
    rightItem->shape.size = (Rect(30.0f, -5.0f, 10.0f, 10.0f)).size;
    rightItem->shape.origin = (Rect(30.0f, -5.0f, 10.0f, 10.0f)).origin + rightItem->shape.pivot * rightItem->shape.size;
    scaledCanvas.addChild(leftItem);
    scaledCanvas.addChild(rightItem);
    scaledCanvas.layout(Rect(scaledCanvas.shape.left(), scaledCanvas.shape.top(), scaledCanvas.shape.size.x, scaledCanvas.shape.size.y));
    leftItem->shape.origin.x = (-4.0f) + leftItem->shape.pivot.x * leftItem->shape.size.x;
    scaledCanvas.refit();
    EOKAS_EXPECT(_FloatEqual(scaledCanvas.shape.left(), 92.0f));
    EOKAS_EXPECT(_FloatEqual(scaledCanvas.shape.size.x, 44.0f));
    EOKAS_EXPECT(_FloatEqual(scaledCanvas.visualRect().size.x, 88.0f));
    EOKAS_EXPECT(_FloatEqual(leftItem->shape.left(), 0.0f));
    EOKAS_EXPECT(_FloatEqual(rightItem->shape.left(), 34.0f));

    UIFrame canvasFrame;
    canvasFrame.init(400, 300);
    auto canvas = std::make_shared<UICanvas>();
    canvas->shape.size = (Rect(100.0f, 50.0f, 0.0f, 0.0f)).size;
    canvas->shape.origin = (Rect(100.0f, 50.0f, 0.0f, 0.0f)).origin + canvas->shape.pivot * canvas->shape.size;
    auto held = std::make_shared<UIWidget>();
    auto loose = std::make_shared<UIWidget>();
    held->shape.size = (Rect(0.0f, 0.0f, 10.0f, 20.0f)).size;
    held->shape.origin = (Rect(0.0f, 0.0f, 10.0f, 20.0f)).origin + held->shape.pivot * held->shape.size;
    loose->shape.size = (Rect(30.0f, -5.0f, 10.0f, 10.0f)).size;
    loose->shape.origin = (Rect(30.0f, -5.0f, 10.0f, 10.0f)).origin + loose->shape.pivot * loose->shape.size;
    loose->dragable = false;
    canvas->addChild(held);
    canvas->addChild(loose);
    canvasFrame.setRoot(canvas);
    canvasFrame.hitTest(0.0f, 0.0f);
    Rect heldBefore = Rect(held->shape.left(), held->shape.top(), held->shape.size.x, held->shape.size.y);
    Rect looseBefore = Rect(loose->shape.left(), loose->shape.top(), loose->shape.size.x, loose->shape.size.y);
    canvasFrame.onMouseDown(120.0f, 65.0f, 0);
    canvasFrame.onMouseMove(130.0f, 70.0f);
    canvasFrame.onMouseUp(130.0f, 70.0f, 0);
    EOKAS_EXPECT(_FloatEqual(held->shape.left(), heldBefore.origin.x));
    EOKAS_EXPECT(_FloatEqual(held->shape.top(), heldBefore.origin.y));
    EOKAS_EXPECT(_FloatEqual(loose->shape.left(), looseBefore.origin.x));
    EOKAS_EXPECT(_FloatEqual(loose->shape.top(), looseBefore.origin.y));
    EOKAS_EXPECT(_FloatEqual(canvas->shape.left(), 110.0f));
    EOKAS_EXPECT(_FloatEqual(canvas->shape.top(), 50.0f));

    canvasFrame.onMouseDown(140.0f, 50.0f, 0);
    canvasFrame.onMouseMove(150.0f, 50.0f);
    canvasFrame.onMouseUp(150.0f, 50.0f, 0);
    EOKAS_EXPECT(_FloatEqual(loose->shape.left(), looseBefore.origin.x));
    loose->dragable = true;
    canvasFrame.onMouseDown(140.0f, 50.0f, 0);
    canvasFrame.onMouseMove(150.0f, 50.0f);
    canvasFrame.onMouseUp(150.0f, 50.0f, 0);
    EOKAS_EXPECT(_FloatEqual(loose->shape.left(), looseBefore.origin.x + 10.0f));
    EOKAS_EXPECT(_FloatEqual(held->shape.left(), heldBefore.origin.x));

    Vector2 focal = Vector2(canvas->shape.left(), canvas->shape.top()) + Vector2(10.0f, 10.0f);
    Vector2 focalLocal = canvas->shape.toLocal(focal);
    Rect looseAtScale = Rect(loose->shape.left(), loose->shape.top(), loose->shape.size.x, loose->shape.size.y);
    canvasFrame.onMouseWheel(focal.x, focal.y, 0.0f, -48.0f);
    Vector2 back = canvas->shape.toParent(Vector2(canvas->shape.left(), canvas->shape.top()) + focalLocal);
    EOKAS_EXPECT(_FloatEqual(back.x, focal.x));
    EOKAS_EXPECT(_FloatEqual(back.y, focal.y));
    EOKAS_EXPECT(_FloatEqual(loose->shape.left(), looseAtScale.origin.x));
    EOKAS_EXPECT(_FloatEqual(loose->shape.top(), looseAtScale.origin.y));
    Vector2 corner(canvas->shape.left(), canvas->shape.top());
    Vector2 cornerLocal = canvas->shape.toLocal(corner);
    canvas->scaleAt(corner, canvas->shape.scale.x * 2.0f);
    Vector2 cornerBack = canvas->shape.toParent(Vector2(canvas->shape.left(), canvas->shape.top()) + cornerLocal);
    EOKAS_EXPECT(std::fabs(cornerBack.x - corner.x) <= 0.0001f);
    EOKAS_EXPECT(std::fabs(cornerBack.y - corner.y) <= 0.0001f);

    auto dragButton = std::make_shared<UIButton>();
    dragButton->setText("OK");
    dragButton->shape.size = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).size;
    dragButton->shape.origin = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).origin + dragButton->shape.pivot * dragButton->shape.size;
    dragButton->dragable = true;
    UICanvas dragGroup;
    dragGroup.addChild(dragButton);
    dragGroup.layout(Rect(0.0f, 0.0f, 0.0f, 0.0f));
    Rect labelRect = Rect(dragButton->label()->shape.left(), dragButton->label()->shape.top(), dragButton->label()->shape.size.x, dragButton->label()->shape.size.y);
    dragGroup.dragChild(dragButton.get(), 5.0f, 6.0f);
    dragGroup.dragChild(dragButton.get(), 15.0f, 9.0f);
    EOKAS_EXPECT(_FloatEqual(dragGroup.shape.left(), 10.0f));
    EOKAS_EXPECT(_FloatEqual(dragGroup.shape.top(), 3.0f));
    EOKAS_EXPECT(_FloatEqual(dragButton->shape.left(), 0.0f));
    EOKAS_EXPECT(_FloatEqual(dragButton->shape.top(), 0.0f));
    EOKAS_EXPECT(_FloatEqual(dragButton->label()->shape.left(), labelRect.origin.x));
    EOKAS_EXPECT(_FloatEqual(dragButton->label()->shape.top(), labelRect.origin.y));

    UIChart triangle;
    triangle.setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    EOKAS_EXPECT(triangle.contains(Vector2(5.0f, 5.0f)));
    EOKAS_EXPECT(!triangle.contains(Vector2(30.0f, 30.0f)));

    UIFrame shapeFrame;
    shapeFrame.init(200, 200);
    auto shapeRoot = std::make_shared<UIWidget>();
    shapeRoot->shape.size = (Rect(0.0f, 0.0f, 200.0f, 200.0f)).size;
    shapeRoot->shape.origin = (Rect(0.0f, 0.0f, 200.0f, 200.0f)).origin + shapeRoot->shape.pivot * shapeRoot->shape.size;
    shapeRoot->pickable = false;
    auto lowerChart = std::make_shared<UIChart>();
    auto upperChart = std::make_shared<UIChart>();
    lowerChart->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(40.0f, 40.0f), Vector2(0.0f, 40.0f) });
    upperChart->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    shapeRoot->children.push_back(lowerChart);
    shapeRoot->children.push_back(upperChart);
    shapeFrame.setRoot(shapeRoot);
    EOKAS_EXPECT(shapeFrame.hitTest(5.0f, 5.0f) == upperChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(30.0f, 5.0f) == upperChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(30.0f, 30.0f) == lowerChart.get());

    auto parentChart = std::make_shared<UIChart>();
    parentChart->setContour({ Vector2(0.0f, 0.0f), Vector2(80.0f, 0.0f), Vector2(0.0f, 80.0f) });
    auto innerChart = std::make_shared<UIChart>();
    innerChart->setContour({ Vector2(4.0f, 4.0f), Vector2(16.0f, 4.0f), Vector2(4.0f, 16.0f) });
    auto outerChart = std::make_shared<UIChart>();
    outerChart->setContour({ Vector2(50.0f, 50.0f), Vector2(70.0f, 50.0f), Vector2(50.0f, 70.0f) });
    parentChart->addChart(innerChart);
    parentChart->addChart(outerChart);
    shapeRoot->children.clear();
    shapeRoot->children.push_back(parentChart);
    EOKAS_EXPECT(shapeFrame.hitTest(6.0f, 6.0f) == innerChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(2.0f, 2.0f) == parentChart.get());
    EOKAS_EXPECT(shapeFrame.hitTest(55.0f, 55.0f) == nullptr);
    parentChart->pickable = false;
    EOKAS_EXPECT(shapeFrame.hitTest(2.0f, 2.0f) == nullptr);
    shapeFrame.quit();

    UIFrame chartFrame;
    chartFrame.init(300, 200);
    auto chartCanvas = std::make_shared<UICanvas>();
    chartCanvas->shape.size = (Rect(0.0f, 0.0f, 300.0f, 200.0f)).size;
    chartCanvas->shape.origin = (Rect(0.0f, 0.0f, 300.0f, 200.0f)).origin + chartCanvas->shape.pivot * chartCanvas->shape.size;
    auto anchor = std::make_shared<UIWidget>();
    anchor->shape.size = (Rect(0.0f, 0.0f, 8.0f, 8.0f)).size;
    anchor->shape.origin = (Rect(0.0f, 0.0f, 8.0f, 8.0f)).origin + anchor->shape.pivot * anchor->shape.size;
    anchor->pickable = false;
    auto picked = std::make_shared<UIChart>();
    auto idle = std::make_shared<UIChart>();
    picked->setContour({ Vector2(20.0f, 20.0f), Vector2(60.0f, 20.0f), Vector2(20.0f, 60.0f) });
    idle->setContour({ Vector2(70.0f, 20.0f), Vector2(110.0f, 20.0f), Vector2(70.0f, 60.0f) });
    chartCanvas->addChild(anchor);
    chartCanvas->addChild(picked);
    chartCanvas->addChild(idle);
    chartFrame.setRoot(chartCanvas);
    int chartClicks = 0;
    int chartDoubles = 0;
    picked->onClick = [&]() { chartClicks += 1; };
    picked->onDoubleClick = [&]() { chartDoubles += 1; };
    chartFrame.onMouseDown(30.0f, 30.0f, 0);
    chartFrame.onMouseUp(30.0f, 30.0f, 0);
    EOKAS_EXPECT(chartClicks == 1);
    EOKAS_EXPECT(picked->selected);
    EOKAS_EXPECT(!idle->selected);
    picked->triggerClick();
    EOKAS_EXPECT(chartDoubles == 1);

    std::vector<Vector2> contourBefore = picked->contour();
    picked->selected = true;
    idle->selected = false;
    chartFrame.onMouseDown(30.0f, 30.0f, 0);
    chartFrame.onMouseMove(42.0f, 30.0f);
    chartFrame.onMouseUp(42.0f, 30.0f, 0);
    EOKAS_EXPECT(chartClicks == 2);
    EOKAS_EXPECT(picked->selected);
    EOKAS_EXPECT(!idle->selected);
    EOKAS_EXPECT(_FloatEqual(picked->shape.left(), contourBefore.empty() ? 0.0f : 32.0f));
    EOKAS_EXPECT(picked->contour().size() == contourBefore.size());
    EOKAS_EXPECT(_FloatEqual(picked->contour()[0].x, contourBefore[0].x));
    EOKAS_EXPECT(_FloatEqual(picked->contour()[0].y, contourBefore[0].y));
    chartFrame.quit();

    UIFrame dropFrame;
    dropFrame.init(300, 120);
    auto dropCanvas = std::make_shared<UICanvas>();
    dropCanvas->shape.size = (Rect(0.0f, 0.0f, 300.0f, 120.0f)).size;
    dropCanvas->shape.origin = (Rect(0.0f, 0.0f, 300.0f, 120.0f)).origin + dropCanvas->shape.pivot * dropCanvas->shape.size;
    auto carried = std::make_shared<UIChart>();
    auto slot = std::make_shared<UIChart>();
    carried->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    slot->setContour({ Vector2(80.0f, 0.0f), Vector2(120.0f, 0.0f), Vector2(80.0f, 40.0f) });
    dropCanvas->addChild(carried);
    dropCanvas->addChild(slot);
    dropFrame.setRoot(dropCanvas);
    int drops = 0;
    UIChart* dropTarget = nullptr;
    carried->onDrop = [&](UIChart* target, float, float) {
        drops += 1;
        dropTarget = target;
    };
    dropFrame.onMouseDown(10.0f, 10.0f, 0);
    dropFrame.onMouseMove(90.0f, 10.0f);
    dropFrame.onMouseUp(90.0f, 10.0f, 0);
    EOKAS_EXPECT(drops == 1);
    EOKAS_EXPECT(dropTarget == slot.get());

    auto plainCanvas = std::make_shared<UICanvas>();
    plainCanvas->shape.size = (Rect(0.0f, 0.0f, 300.0f, 120.0f)).size;
    plainCanvas->shape.origin = (Rect(0.0f, 0.0f, 300.0f, 120.0f)).origin + plainCanvas->shape.pivot * plainCanvas->shape.size;
    auto stone = std::make_shared<UIChart>();
    stone->setContour({ Vector2(60.0f, 0.0f), Vector2(100.0f, 0.0f), Vector2(60.0f, 40.0f) });
    auto plain = std::make_shared<UIWidget>();
    plain->shape.size = (Rect(0.0f, 0.0f, 40.0f, 40.0f)).size;
    plain->shape.origin = (Rect(0.0f, 0.0f, 40.0f, 40.0f)).origin + plain->shape.pivot * plain->shape.size;
    plainCanvas->addChild(stone);
    plainCanvas->addChild(plain);
    dropFrame.setRoot(plainCanvas);
    int plainDrops = 0;
    UIChart* plainTarget = stone.get();
    stone->onDrop = [&](UIChart* target, float, float) {
        plainDrops += 1;
        plainTarget = target;
    };
    dropFrame.onMouseDown(70.0f, 10.0f, 0);
    dropFrame.onMouseMove(10.0f, 10.0f);
    dropFrame.onMouseUp(10.0f, 10.0f, 0);
    EOKAS_EXPECT(plainDrops == 1);
    EOKAS_EXPECT(plainTarget == nullptr);
    dropFrame.quit();

    UIFrame zoomFrame;
    zoomFrame.init(200, 200);
    auto zoomCanvas = std::make_shared<UICanvas>();
    zoomCanvas->shape.size = (Rect(0.0f, 0.0f, 200.0f, 200.0f)).size;
    zoomCanvas->shape.origin = (Rect(0.0f, 0.0f, 200.0f, 200.0f)).origin + zoomCanvas->shape.pivot * zoomCanvas->shape.size;
    auto zoomChart = std::make_shared<UIChart>();
    zoomChart->setContour({ Vector2(0.0f, 0.0f), Vector2(40.0f, 0.0f), Vector2(0.0f, 40.0f) });
    zoomCanvas->addChild(zoomChart);
    zoomFrame.setRoot(zoomCanvas);
    Vector2 zoomFocal(10.0f, 10.0f);
    Vector2 chartLocal = zoomChart->shape.toLocal(zoomFocal);
    zoomFrame.onMouseWheel(10.0f, 10.0f, 0.0f, -48.0f);
    EOKAS_EXPECT(zoomChart->shape.scale.x > 1.0f);
    EOKAS_EXPECT(_FloatEqual(zoomCanvas->shape.scale.x, 1.0f));
    Vector2 zoomBack = zoomChart->shape.toParent(Vector2(zoomChart->shape.left(), zoomChart->shape.top()) + chartLocal);
    EOKAS_EXPECT(_FloatEqual(zoomBack.x, zoomFocal.x));
    EOKAS_EXPECT(_FloatEqual(zoomBack.y, zoomFocal.y));
    Vector2 canvasFocal(180.0f, 180.0f);
    zoomFrame.onMouseWheel(canvasFocal.x, canvasFocal.y, 0.0f, -48.0f);
    EOKAS_EXPECT(zoomCanvas->shape.scale.x > 1.0f);
    EOKAS_EXPECT(_FloatEqual(zoomChart->visualRect().origin.x, 0.0f));
    EOKAS_EXPECT(_FloatEqual(zoomChart->visualRect().origin.y, 0.0f));
    zoomFrame.quit();

    UIEllipse ellipse;
    ellipse.shape.size = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).size;
    ellipse.shape.origin = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).origin + ellipse.shape.pivot * ellipse.shape.size;
    EOKAS_EXPECT(ellipse.contains(Vector2(20.0f, 10.0f)));
    EOKAS_EXPECT(ellipse.contains(Vector2(40.0f, 10.0f)));
    EOKAS_EXPECT(!ellipse.contains(Vector2(0.0f, 0.0f)));
    EOKAS_EXPECT(_FloatEqual(ellipse.shape.size.x, 40.0f));
    EOKAS_EXPECT(_FloatEqual(ellipse.shape.size.y, 20.0f));
    UIPrimitive ellipsePrimitive;
    ellipsePrimitive.begin();
    ellipse.render(ellipsePrimitive);
    ellipsePrimitive.end();
    uint32_t fillCount = ellipsePrimitive.indexCount;
    ellipse.stroke.thickness = 2.0f;
    ellipse.selected = true;
    ellipsePrimitive.begin();
    ellipse.render(ellipsePrimitive);
    ellipsePrimitive.end();
    EOKAS_EXPECT(ellipsePrimitive.indexCount > fillCount);

    UIRectangle chartBox;
    chartBox.shape.size = (Rect(10.0f, 20.0f, 40.0f, 20.0f)).size;
    chartBox.shape.origin = (Rect(10.0f, 20.0f, 40.0f, 20.0f)).origin + chartBox.shape.pivot * chartBox.shape.size;
    EOKAS_EXPECT(chartBox.contains(Vector2(10.0f, 20.0f)));
    EOKAS_EXPECT(chartBox.contains(Vector2(30.0f, 30.0f)));
    EOKAS_EXPECT(chartBox.contains(Vector2(50.0f, 40.0f)));
    EOKAS_EXPECT(!chartBox.contains(Vector2(9.0f, 30.0f)));

    UIDiamond diamond;
    diamond.shape.size = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).size;
    diamond.shape.origin = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).origin + diamond.shape.pivot * diamond.shape.size;
    EOKAS_EXPECT(diamond.contains(Vector2(20.0f, 10.0f)));
    EOKAS_EXPECT(diamond.contains(Vector2(20.0f, 0.0f)));
    EOKAS_EXPECT(diamond.contains(Vector2(40.0f, 10.0f)));
    EOKAS_EXPECT(!diamond.contains(Vector2(0.0f, 0.0f)));
    EOKAS_EXPECT(!diamond.contains(Vector2(40.0f, 0.0f)));

    auto from = std::make_shared<UIRectangle>();
    auto to = std::make_shared<UIRectangle>();
    from->shape.size = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).size;
    from->shape.origin = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).origin + from->shape.pivot * from->shape.size;
    to->shape.size = (Rect(80.0f, 0.0f, 40.0f, 20.0f)).size;
    to->shape.origin = (Rect(80.0f, 0.0f, 40.0f, 20.0f)).origin + to->shape.pivot * to->shape.size;
    UILink link;
    link.kind = UIPathKind::Straight;
    link.setPoints({ Vector2(40.0f, 10.0f), Vector2(80.0f, 10.0f) });
    link.line.thickness = 2.0f;
    link.hitSlop = 4.0f;
    EOKAS_EXPECT(link.contains(Vector2(60.0f, 10.0f)));
    EOKAS_EXPECT(!link.contains(Vector2(60.0f, 30.0f)));
    UIFrame linkFrame;
    linkFrame.init(200, 80);
    auto linkRoot = std::make_shared<UIWidget>();
    linkRoot->shape.size = (Rect(0.0f, 0.0f, 200.0f, 80.0f)).size;
    linkRoot->shape.origin = (Rect(0.0f, 0.0f, 200.0f, 80.0f)).origin + linkRoot->shape.pivot * linkRoot->shape.size;
    linkRoot->pickable = false;
    auto hitLink = std::make_shared<UILink>();
    hitLink->setPoints({ Vector2(40.0f, 10.0f), Vector2(80.0f, 10.0f) });
    hitLink->line.thickness = 2.0f;
    hitLink->hitSlop = 4.0f;
    linkRoot->children.push_back(hitLink);
    linkFrame.setRoot(linkRoot);
    EOKAS_EXPECT(hitLink->contains(Vector2(60.0f, 12.0f)));
    EOKAS_EXPECT(!Rect(hitLink->shape.left(), hitLink->shape.top(), hitLink->shape.size.x, hitLink->shape.size.y).contains(Vector2(60.0f, 12.0f)));
    EOKAS_EXPECT(linkFrame.hitTest(60.0f, 12.0f) == hitLink.get());
    linkFrame.quit();
    link.start.target = from.get();
    link.start.anchor = UIAnchor::Right;
    link.end.target = to.get();
    link.end.anchor = UIAnchor::Left;
    EOKAS_EXPECT(link.contains(Vector2(60.0f, 10.0f)));
    to->shape.origin = (Vector2(80.0f, 40.0f)) + to->shape.pivot * to->shape.size;
    EOKAS_EXPECT(link.contains(Vector2(60.0f, 30.0f)));
    EOKAS_EXPECT(!link.contains(Vector2(60.0f, 10.0f)));

    from->shape.size = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).size;
    from->shape.origin = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).origin + from->shape.pivot * from->shape.size;
    to->shape.size = (Rect(80.0f, 40.0f, 40.0f, 20.0f)).size;
    to->shape.origin = (Rect(80.0f, 40.0f, 40.0f, 20.0f)).origin + to->shape.pivot * to->shape.size;
    UILink curve;
    curve.kind = UIPathKind::CubicBezier;
    curve.setPoints({
        Vector2(40.0f, 10.0f),
        Vector2(50.0f, -40.0f),
        Vector2(70.0f, 80.0f),
        Vector2(80.0f, 10.0f)
    });
    curve.line.thickness = 2.0f;
    curve.hitSlop = 3.0f;
    curve.start.target = from.get();
    curve.start.anchor = UIAnchor::Right;
    curve.end.target = to.get();
    curve.end.anchor = UIAnchor::Left;
    EOKAS_EXPECT(curve.contains(Vector2(44.0f, 10.0f)));
    EOKAS_EXPECT(curve.contains(Vector2(76.0f, 50.0f)));
    EOKAS_EXPECT(!curve.contains(Vector2(48.0f, -20.0f)));

    UIRectangle cornerBox;
    cornerBox.shape.size = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).size;
    cornerBox.shape.origin = (Rect(0.0f, 0.0f, 40.0f, 20.0f)).origin + cornerBox.shape.pivot * cornerBox.shape.size;
    cornerBox.border.thickness = 2.0f;
    UIPrimitive cornerPrimitive;
    cornerPrimitive.begin();
    cornerBox.render(cornerPrimitive);
    cornerPrimitive.end();
    EOKAS_EXPECT(cornerPrimitive.indexCount == 54);

    canvasFrame.quit();

    UIShape defaults;
    EOKAS_EXPECT(_FloatEqual(defaults.pivot.x, 0.5f));
    EOKAS_EXPECT(_FloatEqual(defaults.pivot.y, 0.5f));
    EOKAS_EXPECT(_FloatEqual(defaults.scale.x, 1.0f));
    EOKAS_EXPECT(_FloatEqual(defaults.scale.y, 1.0f));
    EOKAS_EXPECT(_FloatEqual(defaults.origin.x, 0.0f));
    EOKAS_EXPECT(_FloatEqual(defaults.origin.y, 0.0f));
    EOKAS_EXPECT(_FloatEqual(defaults.left(), 0.0f));
    EOKAS_EXPECT(_FloatEqual(defaults.top(), 0.0f));

    UIShape edges;
    edges.size = Vector2(10.0f, 8.0f);
    edges.origin = Vector2(1.0f, 2.0f) + edges.pivot * edges.size;
    EOKAS_EXPECT(_FloatEqual(edges.origin.x, 6.0f));
    EOKAS_EXPECT(_FloatEqual(edges.origin.y, 6.0f));
    EOKAS_EXPECT(_FloatEqual(edges.left(), 1.0f));
    EOKAS_EXPECT(_FloatEqual(edges.top(), 2.0f));
    edges.setLeft(4.0f);
    EOKAS_EXPECT(_FloatEqual(edges.left(), 4.0f));
    EOKAS_EXPECT(_FloatEqual(edges.right(), 11.0f));
    EOKAS_EXPECT(_FloatEqual(edges.size.x, 7.0f));
    EOKAS_EXPECT(_FloatEqual(edges.origin.x, 7.5f));
    edges.setRight(20.0f);
    EOKAS_EXPECT(_FloatEqual(edges.left(), 4.0f));
    EOKAS_EXPECT(_FloatEqual(edges.size.x, 16.0f));
    EOKAS_EXPECT(_FloatEqual(edges.origin.x, 12.0f));
    edges.setTop(5.0f);
    EOKAS_EXPECT(_FloatEqual(edges.top(), 5.0f));
    EOKAS_EXPECT(_FloatEqual(edges.bottom(), 10.0f));
    EOKAS_EXPECT(_FloatEqual(edges.size.y, 5.0f));
    EOKAS_EXPECT(_FloatEqual(edges.origin.y, 7.5f));
    edges.setBottom(12.0f);
    EOKAS_EXPECT(_FloatEqual(edges.top(), 5.0f));
    EOKAS_EXPECT(_FloatEqual(edges.size.y, 7.0f));
    EOKAS_EXPECT(_FloatEqual(edges.origin.y, 8.5f));
    EOKAS_EXPECT(_FloatEqual(edges.pivot.x, 0.5f));
    EOKAS_EXPECT(_FloatEqual(edges.pivot.y, 0.5f));

    UIShape zoomed;
    zoomed.size = Vector2(10.0f, 10.0f);
    zoomed.origin = Vector2(0.0f, 0.0f) + zoomed.pivot * zoomed.size;
    EOKAS_EXPECT(_FloatEqual(zoomed.origin.x, 5.0f));
    EOKAS_EXPECT(_FloatEqual(zoomed.origin.y, 5.0f));
    zoomed.scale = Vector2(2.0f, 2.0f);
    Vector2 visualCorner = zoomed.toParent(Vector2(zoomed.left(), zoomed.top()));
    EOKAS_EXPECT(_FloatEqual(visualCorner.x, -5.0f));
    EOKAS_EXPECT(_FloatEqual(visualCorner.y, -5.0f));
    Rect visual = zoomed.visualRect();
    EOKAS_EXPECT(_FloatEqual(visual.origin.x, -5.0f));
    EOKAS_EXPECT(_FloatEqual(visual.origin.y, -5.0f));
    EOKAS_EXPECT(_FloatEqual(visual.size.x, 20.0f));
    EOKAS_EXPECT(_FloatEqual(visual.size.y, 20.0f));
    Vector2 pivotParent = zoomed.toParent(zoomed.origin);
    EOKAS_EXPECT(_FloatEqual(pivotParent.x, 5.0f));
    EOKAS_EXPECT(_FloatEqual(pivotParent.y, 5.0f));
    Vector2 aroundBefore = zoomed.toUnscaled(Vector2(5.0f, 5.0f));
    zoomed.scaleAround(Vector2(5.0f, 5.0f), Vector2(4.0f, 4.0f));
    Vector2 aroundAfter = zoomed.toUnscaled(Vector2(5.0f, 5.0f));
    EOKAS_EXPECT(_FloatEqual(aroundBefore.x, aroundAfter.x));
    EOKAS_EXPECT(_FloatEqual(aroundBefore.y, aroundAfter.y));
    EOKAS_EXPECT(_FloatEqual(zoomed.origin.x, 5.0f));
    EOKAS_EXPECT(_FloatEqual(zoomed.origin.y, 5.0f));

    UIShape cornerPivot;
    cornerPivot.pivot = Vector2(0.0f, 0.0f);
    cornerPivot.origin = Vector2(0.0f, 0.0f);
    cornerPivot.scale = Vector2(1.0f, 1.0f);
    cornerPivot.scaleAround(Vector2(10.0f, 10.0f), Vector2(2.0f, 2.0f));
    EOKAS_EXPECT(_FloatEqual(cornerPivot.origin.x, -10.0f));
    EOKAS_EXPECT(_FloatEqual(cornerPivot.origin.y, -10.0f));

    return 0;
}
