
set(EOKAS_TARGET_NAME "render")
set(EOKAS_TARGET_DIR "${EOKAS_MODULES_DIR}/${EOKAS_TARGET_NAME}")

message("EOKAS_TARGET_NAME = ${EOKAS_TARGET_NAME}")
message("EOKAS_TARGET_DIR = ${EOKAS_TARGET_DIR}")

set(EOKAS_HEADER_DIRS
        "${EOKAS_MODULES_DIR}"
)

set(EOKAS_LIBRARY_DIRS
        "${EOKAS_PROJECT_DIR}/deps/lib/${EOKAS_OS_NAME}/${CMAKE_BUILD_TYPE}"
)

file(GLOB EOKAS_HEADER_FILES
        "${EOKAS_TARGET_DIR}/*.h"
)

file(GLOB EOKAS_SOURCE_FILES
        "${EOKAS_TARGET_DIR}/*.cpp"
        "${EOKAS_TARGET_DIR}/${EOKAS_OS_NAME}/*.cpp"
)

set(EOKAS_LIBRARY_FILES
        "base" "gpu" "mesh"
)

message("EOKAS_HEADER_DIRS = ${EOKAS_HEADER_DIRS}")
message("EOKAS_LIBRARY_DIRS = ${EOKAS_LIBRARY_DIRS}")
message("EOKAS_HEADER_FILES = ${EOKAS_HEADER_FILES}")
message("EOKAS_SOURCE_FILES = ${EOKAS_SOURCE_FILES}")
message("EOKAS_LIBRARY_FILES = ${EOKAS_LIBRARY_FILES}")

if(NOT EOKAS_SOURCE_FILES)
    # 源码尚未落地：空 STATIC 库无法配置，先占住同名 target。
    add_library(${EOKAS_TARGET_NAME} INTERFACE)
    target_include_directories(${EOKAS_TARGET_NAME} INTERFACE ${EOKAS_HEADER_DIRS})
    target_link_libraries(${EOKAS_TARGET_NAME} INTERFACE ${EOKAS_LIBRARY_FILES})
else()
    add_library(${EOKAS_TARGET_NAME} STATIC ${EOKAS_HEADER_FILES} ${EOKAS_SOURCE_FILES})
    target_include_directories(${EOKAS_TARGET_NAME} PRIVATE ${EOKAS_HEADER_DIRS})
    target_link_directories(${EOKAS_TARGET_NAME} PRIVATE ${EOKAS_LIBRARY_DIRS})
    target_link_libraries(${EOKAS_TARGET_NAME} ${EOKAS_LIBRARY_FILES})

    install(FILES ${EOKAS_HEADER_FILES} DESTINATION include/${EOKAS_TARGET_NAME})
    install(TARGETS ${EOKAS_TARGET_NAME} DESTINATION lib/${EOKAS_OS_NAME}/${CMAKE_BUILD_TYPE})
endif()
